branches:
  except:
    - gh-pages
language: perl6
sudo: false
perl6:
  - latest
install:
  - rakudobrew build-zef
  - zef install Test::META
  - zef install Path::Iterator
  - zef install TAP::Harness
  - zef install Crypt::Random
  - zef install Crypt::Bcrypt
  - zef install DBIish
#  - zef install Bailador

  - zef install HTTP::Easy
  - zef -v info HTTP::Easy
  - zef install Log::Any
  - zef -v info Log::Any
  - zef install Template::Mojo
  - zef install Terminal::ANSIColor
  - zef -v install https://github.com/Bailador/Bailador/archive/dev.tar.gz
  - zef install Email::Valid
  - zef install LWP::Simple
  - zef install IO::Socket::SSL
#  - zef install Redis
#  - zef install MongoDB

