branches:
  except:
    - gh-pages
language: perl6
sudo: false
perl6:
  - latest
install:
  - rakudobrew build-zef
  - zef install Test::META
  - zef install Path::Iterator
  - zef install TAP::Harness
  - zef install Crypt::Random
  - zef install Crypt::Bcrypt
  - zef install DBIish
  - zef install Bailador
  - zef install Email::Valid
  - zef install LWP::Simple
  - zef install IO::Socket::SSL
#  - zef install Redis
#  - zef install MongoDB

